
// DEFINE ACTIONS TYPE
const UserActionTypes = {
    FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
    FETCH_USERS_SUCESS: 'FETCH_USERS_SUCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',
}

export default{
    ...UserActionTypes
}